### ISSUE TITLE
Provide instructions to set up KEYS

### ISSUE THREAD

**Issue by jacobjj** [jakeypakey/ECE_229_project#1]
Provide set of instructions to set up KEYS.

**Comment by EugeneLi5237** [comment]
Hi, I have made a private post about the key. Sorry for the inconvenience.

**Comment by jacobjj** [comment]
Sorry, where should I look for setting up the Keys?

**Comment by EugeneLi5237** [comment]
Sorry, my bad. I made a private post on piazza @240. Sorry for the inconvenience.
